# Generated by Django 4.2.5 on 2023-11-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="accepted_eula",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="favorite_animal",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="isExpert",
            field=models.BooleanField(default=False),
        ),
    ]
