# Generated by Django 4.2.5 on 2023-11-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="expertinfo",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
