# Generated by Django 4.2.5 on 2023-11-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OpenRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_room_name", models.CharField(max_length=50)),
                ("chat_room_url", models.URLField()),
            ],
        ),
    ]
