# Generated by Django 4.2.5 on 2023-11-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openroom',
            name='chat_room_url',
            field=models.CharField(max_length=200),
        ),
    ]
